### ISSUE TITLE
get node returns new message

### ISSUE THREAD

**Issue by boisei0** [deconz-community/node-red-contrib-deconz#124]
** Describe issue **
The `get` node returns a new message, rather than adding the values to the existing message object. This means that this node can't be used next to the http-in/http-response nodes, as it will remove the `msg.res` object from the message. 
https://github.com/deconz-community/node-red-contrib-deconz/blob/a5127c2214f0c754d9856e59f7e86617c5d61bcb/nodes/get.js#L73-L77 
Rather, it should edit the current msg object and return it with `node.send`, as is the best-practice approach. 

** Hardware / Software **
  - raspberry pi 3 B+   
  - version of deconz gateway: [2.05.72 / 12-12/2019] 
  - version of node-red-contrib-deconz: [1.2.0]

**Comment by Zehir** [comment]
I dit not know this best practice where did you see that?

**Comment by Steve-Mcl** [comment]
Hi @Zehir, I hope you dont mind me joining the conversation.  

It is best practice to re-use the incoming msg so that other properties are not discarded.  

In an ideal situation, a user sets a property in the msg (e.g. `msg.topic`), passes the msg to the next node then the next etc & down stream the user hopes to access the original `msg.topic` property he added at the beginning so he can send it to the MQTT out node.  If the original msg is discarded, the user has to jump through hoops (i.e. store a value in context - that can cause all sorts of concurrency issues when multiple messages are in transit)  

Also, If your contrib node always discards the original msg, users will not be able to use it (easily) in conjunction with many other other nodes that follow this pattern...
the HTTP IN / HTTP OUT nodes, the TCP IN / TCP OUT nodes, the SPLIT and JOIN nodes (and many others) all expect the original message to arrive at the other side to work correctly since there is important meta data in the msg to help them process it.

**Comment by Zehir** [comment]
> Hi @Zehir, I hope you dont mind me joining the conversation.  
> 
> It is best practice to re-use the incoming msg so that other properties are not discarded.  
> 
> In an ideal situation, a user sets a property in the msg (e.g. `msg.topic`), passes the msg to the next node then the next etc & down stream the user hopes to access the original `msg.topic` property he added at the beginning so he can send it to the MQTT out node.  If the original msg is discarded, the user has to jump through hoops (i.e. store a value in context - that can cause all sorts of concurrency issues when multiple messages are in transit)  
> 
> Also, If your contrib node always discards the original msg, users will not be able to use it (easily) in conjunction with many other other nodes that follow this pattern...
> the HTTP IN / HTTP OUT nodes, the TCP IN / TCP OUT nodes, the SPLIT and JOIN nodes (and many others) all expect the original message to arrive at the other side to work correctly since there is important meta data in the msg to help them process it. 
> 
> 

Ok but the node set more data that only payload, what do I do if the input use a key that I will replace ?

**Comment by Steve-Mcl** [comment]
> Ok but the node set more data that only payload, what do I do if the input use a key that I will replace ?

thats fine. Just avoid 9if you can) overwriting things like...
* `.parts`
* `.res`
* `.req`
* `.topic` (unless it makes sense to)
* `.filename` (unless it makes sense to)

And importantly, document what props our node writes to in the built in help - that way, the user at least can *move* the property to something else (while its transmitted through your node) e.g. `msg.__steves_ip_temp` then when the msg gets to the other side of your node, I can move `msg.__steves_ip_temp` back into `msg.ip` - the point is really to NOT discard the oiginal msg. This avoids the nasty concurrency issues faced when using context to get past this issue.

Thanks for the consideration.

**Comment by Zehir** [comment]
Sure that not hard to do, it's will part of #120 or just after.
And if the message generate pluviale output, should the msg id the same of a unique one ?

**Comment by Steve-Mcl** [comment]
> should the msg id the same of a unique one 
You leave the msg id - node-red takes care of that.  Just set your props in the original msg.
