### ISSUE TITLE
WebSocket disconnected: 1000

### ISSUE THREAD

**Issue by arozhankov** [deconz-community/node-red-contrib-deconz#165]
### Current Behavior

After last update at Deploy I have this error: WebSocket disconnected: 1000
but all works fine .....

Previously it was: https://github.com/deconz-community/node-red-contrib-deconz/issues/146

### Environment

- deCONZ plugin version: 2.0.8
- Node-RED version: 1.3.7 (last for iobroker)
- Node.js version: v12.22.5
- npm version: 8.1.3
- Platform/OS: Debian 11.1
- Browser: Safari and Chrome

**Comment by TheNON75** [comment]
Hi @arozhankov 
Does this happen with full deploy only or in other cases too?

**Comment by arozhankov** [comment]
> Hi @arozhankov
> Does this happen with full deploy only or in other cases too?

with full deploy

**Comment by Zehir** [comment]
This mean that at some point the connexion between node-red plugin and deconz websocket was lost. The connexion came back in second so that why it's working fine. The last error is displayed on the node until a new event is passing throught the node. I need to change this beavior but I don't know how yet.
Maybe I will remove server error of the nodes and put them in a new node a in a mode of the event node.

**Comment by TheNON75** [comment]
I believe it is perfectly fine in case of a "full deploy" or "restart nodes"

;)

**Comment by Zehir** [comment]
> I believe it is perfectly fine in case of a "full deploy" or "restart nodes"
> 
> ;)

Yes when you deploy the websocket is shutdown so it's trigger the error event but this should be ignored and not sent to the user

**Comment by TheNON75** [comment]
> > I believe it is perfectly fine in case of a "full deploy" or "restart nodes"
> 
> > 
> 
> > ;)
> 
> 
> 
> Yes when you deploy the websocket is shutdown so it's trigger the error event but this should be ignored and not sent to the user

You are a perfectionist, I like it 😉
